name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch (e.g., master or main)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (optional)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (optional)
        run: |
          npm install

      - name: Build project (optional)
        run: |
          npm run build  # Add this if your project requires a build step

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Change this if your built files are in a different directory (e.g., "dist")
